
#································
# API SERVER CONFIG
#································
API_SERVER:
  AUTH_MODULE: demo-auth

#································
# ... or API Client settings
#································
API_CLIENT:
  0:
    URL: https://api.domain.com
    HEADER: API_HEADER # session[api_header][]
