
#································
# API SERVER CONFIG
#································
API_SERVER:
  AUTH_MODULE: auth

#································
# API Client settings
#································
API_CLIENT: false