
#································
# API SERVER CONFIG
#································
API_SERVER:
  AUTH_MODULE: api-server-auth

#································
# API Client settings
#································
API_CLIENT: false