#································
# App settings
#································
PROJECT: Arion Test Project
NAME: arion
URL: https://arion.appixar.com
DYNAMIC_SUB_DOMAIN: false
DEV: true

#································
# <ROUTE> build flow
#································
# Main build (/index.php)
FLOW: 
  - /auth-verify.php
  - <ROUTE>.php
  - /header.tpl
  - <ROUTE>.tpl
  - /footer-start.tpl
  - scripts.tpl
  - /footer-end.tpl
# Build inside another build (routes/page.tpl: <?php $arion->build('_snippets/page') ?>)
FLOW_INNER:
  - <ROUTE>.php
  - <ROUTE>.tpl

#································
# <PAGE> url aliases
#································
ALIAS: false

#································
# Auto include .css & .js files
#································
# <PAGE>.css & <PAGE>.js will be auto included with buffer handling,
# accepting php commands and accessing $_APP global variables
INCLUDE_CSS_JS: false 

#·····································
# Auto incl. /libs (/* to all)
#·····································
DEFAULT_LIBS: 
  - uitools
  - helpers

#·····································
# Auto incl. /modules (/* to all)
#·····································
DEFAULT_MODULES: 
  - auth
  - mmn

#·····································
# Dev tools
#·····································
DEBUG: true