#································
# Database settings
#································
MYSQL:
  0:
    PORT: 3306
    NAME: qmz
    HOST: db.qmoleza.com
    USER: admin
    PASS: 791135b1a919d8d22bc4f33b943499a641494440670e587c
    PREF: share_ # TABLES PREFIX
    PATH: app/database/schema/ # FOR CMD: MASON DATABASE UP
  'dynamic':
    PORT: 3306
    NAME: qmz_% # % = WILDCARD VARIABLE
    HOST: db.qmoleza.com # % = WILDCARD
    USER: admin
    PASS: 791135b1a919d8d22bc4f33b943499a641494440670e587c
    PREF: qmz_
    PATH: app/database/schema/dynamic/ # FOR CMD: MASON DATABASE UP
    # WILDCARD LOOP (MASON DATABASE UP)
    WILD:
      KEY: 0
      TABLE: qmz_company
      FIELD: com_code
      WHERE: com_status > 0