#································
# Database settings
#································
MYSQL:
  0:
    PORT: 3306
    NAME: apx_test
    HOST: localhost
    USER: appixar
    PASS: 4pp1x4r.777@---
    PREF: ox_ # TABLES PREFIX
    #PATH: app/database/ # FOR CMD: MASON DATABASE UP. DEPRECATED(DISTRIB PATH)