
#································
# API SERVER CONFIG
#································
API_SERVER:
  AUTH_MODULE: api-server-auth

#································
# API Client settings
#································
API_CLIENT: false
#API_CLIENT:
#  0:
#    URL: https://api.qmoleza.com
#    HEADER: API_HEADER # session[api_header][]