#································
# Database settings
#································
MYSQL:
  0:
    PORT: 3306
    NAME: apx_oxcoin
    HOST: localhost
    USER: appixar
    PASS: 
    PREF: ox_ # TABLES PREFIX
    PATH: app/database/schema/ # FOR CMD: MASON DATABASE UP