AUTH:
  # MODES:
  # CHECK DB IN EVERY REQUEST...
  #   SKR = SINGLE KEY REFRESH(USER_KEY REFRESH EVERY REQUEST)
  #   SKS = SINGLE KEY STATIC(KEY REFRESH MANNUALY OR EVERY X TIME)
  #   MKS = MULTI KEYS STATIC + SESSION CONTROL
  # DONT CHECK DB...
  #   JWT (CONFIGURABLE)
  MODE: SKR